name: Build and Deploy Frontend

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/aurifi-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/aurifi-frontend:${{ github.sha }}

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Add this line
        script: |
          cd /opt/aurifi
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aurifi-frontend:latest
          docker compose stop frontend
          docker compose up -d frontend
          docker image prune -f
          echo "✅ Frontend deployed successfully!"